spring:
  profiles:
    active: local
  application:
    name: eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server2:8761/eureka/,http://eureka-server3:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
server:
  port: 8761